# -*- coding: utf-8 -*-
"""clean water sanitization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZgY482wHrxWav-TbDBikNu_lOl2W1LRA
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Load the data with a more tolerant encoding
data = pd.read_csv('Water_quality.csv', encoding='ISO-8859-1')

# Display the first few rows and column names to understand the data structure
data.head()
data.columns

# Check for missing values
data.isnull().sum()
# Check the available columns
data.columns

# Plotting Temperature (Max) over the station codes using Matplotlib
plt.figure(figsize=(10, 6))
plt.plot(data['STN\nCode'], data['Temperature\n?C (Max)'], marker='o')
plt.title('Maximum Temperature Over Station Codes')
plt.xlabel('Station Code')
plt.ylabel('Temperature (Max) in °C')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Histogram for Temperature (Max) using Matplotlib
plt.figure(figsize=(10, 6))
sns.histplot(data['Temperature\n?C (Max)'], bins=30, kde=True)
plt.title('Distribution of Maximum Temperature Levels')
plt.xlabel('Temperature (Max) in °C')
plt.ylabel('Frequency')
plt.show()

# Boxplot for pH (Max) using Matplotlib
plt.figure(figsize=(10, 6))
sns.boxplot(x=data['pH (Max)'])
plt.title('Boxplot of pH Levels (Max)')
plt.xlabel('pH (Max)')
plt.ylabel('Levels')
plt.show()

# Interactive line plot for Temperature (Max) over station codes
fig = px.line(data, x='STN\nCode', y='Temperature\n?C (Max)', title='Interactive Maximum Temperature Over Station Codes')
fig.update_xaxes(title_text='Station Code')
fig.update_yaxes(title_text='Temperature (Max) in °C')
fig.show()

# Interactive histogram for Temperature (Max)
fig = px.histogram(data, x='Temperature\n?C (Max)', nbins=30, title='Interactive Distribution of Maximum Temperature Levels')
fig.update_xaxes(title_text='Temperature (Max) in °C')
fig.update_yaxes(title_text='Frequency')
fig.show()

# Interactive boxplot for pH (Max)
fig = px.box(data, y='pH (Max)', title='Interactive Boxplot of pH Levels (Max)')
fig.update_yaxes(title_text='pH (Max)')
fig.show()